### ISSUE TITLE
Update OS_TimerSet API documentation for timer disable

### ISSUE THREAD

**Issue by skliper** [nasa/osal#10]
**Is your feature request related to a problem? Please describe.**
As stated in #9, the OS_TimerSet documentation does not match behavior.

**Describe the solution you'd like**
API documentation should describe OS_TimerDelete() as the method to cancel the timer (not a start time of zero)

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman/NASA-GSFC

**Comment by avan989** [comment]
I'll do this.
