### ISSUE TITLE
network-api-test timeout still too short for MCP750

### ISSUE THREAD

**Issue by jphickey** [nasa/osal#1086]
**Describe the bug**
The console/printf operations on MCP750 take a considerable amount of time (only 9600 baud serial).  It appears some extra assert statements added in this test have made it so even 1000ms is not sufficient.  (looks like the ServerFn might be timing out on a write while the client is printing a bunch of asserts, which then causes an error later when the client finally gets to the read).

**To Reproduce**
Run test on MCP750, observe unexpected timeout error:

    [ FAIL] 04.040 network-api-test.c:680 - OS_TimedRead() (-4) == 4

**Expected behavior**
Test should pass

**System observed on:**
MCP750 VxWorks 6.9

**Reporter Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by jphickey** [comment]
Bumping the timeout up to 4000ms seems to fix the issue.... so this is what I'd propose.

**Comment by skliper** [comment]
Concur.
