### ISSUE TITLE
Return OS_ERROR if OS_TimerSet is called with both parameters as zero

### ISSUE THREAD

**Issue by skliper** [nasa/osal#11]
**Is your feature request related to a problem? Please describe.**
Related to the discussion in #9

**Describe the solution you'd like**
See title, as described in https://github.com/nasa/osal/issues/9#issuecomment-528071853

**Describe alternatives you've considered**
See #9 comment thread

**Additional context**
None

**Requester Info**
Jacob Hageman/NASA-GSFC

**Comment by avan989** [comment]
I'll do this.

**Comment by avan989** [comment]
I need a little more clarification on this. There are 3 files that contains OS_TimerSet. Is the fix asking to change in all 3 (psix, rtems, vxworks6) or just in rtems?

**Comment by jphickey** [comment]
Be sure to do a "pull" first.  The merge from rc-5.0.0 happened recently.  You should find just one implementation of this function in the "shared" directory.
