### ISSUE TITLE
Unreachable branch on unknown fstype in `OS_FileSys_Initialize`

### ISSUE THREAD

**Issue by skliper** [nasa/osal#1107]
**Is your feature request related to a problem? Please describe.**
`filesys->fstype == OS_FILESYS_TYPE_UNKNOWN` is always true due to memset of filesys to zero in `OS_OBJECT_INIT` call.  Nothing else can logically set it otherwise or reason to not set if the other conditions are true.
https://github.com/nasa/osal/blob/cb95655f1743890835a10847439380b5ef7e31a0/src/os/shared/src/osapi-filesys.c#L176-L188

**Describe the solution you'd like**
Remove dead branch.

**Describe alternatives you've considered**
Clear justification for leaving in.

**Additional context**
None.

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
I concur on removing the conditional and assuming it is always `OS_FILESYS_TYPE_VOLATILE_DISK` in the current implementation.

This helper function is only used as part of `OS_initfs` and `OS_mkfs` and both of these public APIs are only intended to set up RAM disks.  Non-volatile storage now uses a separate registration such as `OS_FileSysAddFixedMap()`.  I think originally this code was also used for translating entries in the volume table, but that is no longer the case.
