### ISSUE TITLE
Enforce branch coverage in workflow (set limit on uncovered branches)

### ISSUE THREAD

**Issue by skliper** [nasa/osal#1115]
**Is your feature request related to a problem? Please describe.**
#1114 gets us down to 4 uncovered branches (with issues for each), need to enforce so this doesn't slip w/ future updates.

**Describe the solution you'd like**
Workflow currently checks for 100% line coverage:
https://github.com/nasa/osal/blob/f11d04961d0410af1adb6a2202549b195be3fa5a/.github/workflows/local_unit_test.yml#L35-L41

Add check of branches, suggesting reading in the branches*(AAA of BBB branches) and confirming BBB-AAA <= 4 (suggesting the bash math support to keep things simple).

**Describe alternatives you've considered**
Minimum % coverage is somewhat weak since it doesn't really catch if you add more uncovered branches (as long as you add enough covered ones also).  Hard count check is better.  Really getting to 100% is even better, but we aren't there yet.

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by nmullane** [comment]
I'll start working on this.
