### ISSUE TITLE
vxworks osapi.c utility task doesn't exit

### ISSUE THREAD

**Issue by skliper** [nasa/osal#120]
The vxworks osapi.c has an optional task that is started in OS_API_Init():
```
/*---------------------------------------------------------------------------
 * Name:    UtilityTask
 * Purpose: If turned on, this task will print out the messages from
 *          the OS_printf buffer at a low priority. This will mean
 *          that the functions calling OS_printf will not block due to
 *          writing data to the UART
----------------------------------------------------------------------------*/
#ifdef OS_UTILITY_TASK_ON
void UtilityTask()
...
```

However, this utility task implementation has a while(TRUE) loop with no exit logic.  For a "load and forever run it" scenario this may work, but for any other scenario where an orderly shutdown is desired by the user this means the task is never killed.  One can get kernel crashes if the vxworks module is unloaded while that thread is still writing to output.  The forever loop thread also makes line coverage difficult.

We need a robust method to always end this thread and to ensure the parent thread doesn't return to OS control while this thread is still hanging out there.

**Comment by skliper** [comment]
_Imported from trac issue 97.  Created by abrown4 on 2015-08-31T14:30:11, last modified: 2019-08-14T14:11:46_

**Comment by skliper** [comment]
_Trac comment by abrown4 on 2015-11-25 17:11:19:_

See also #56, which adds an OS_ApplicationShutdown() and may run into the same issue when/if those changes are ported over to VxWorks.

**Comment by skliper** [comment]
Note OS_ConsoleTask_Entry in posix/osapi.c is still a while(true) loop with no exit.

VxWorks task exits on semTake failure.  I think that means this task will exit if the semaphore is deleted, but I also don't see it being deleted.

**Comment by jphickey** [comment]
There may be a simple fix here, by just checking the `ShutdownFlag` in the while loop.
