### ISSUE TITLE
Enforce commit message name rule as githook

### ISSUE THREAD

**Issue by thesamprice** [nasa/osal#1296]
**Is your feature request related to a problem? Please describe.**
Enforce commit message name rule as githook

I'm always frustrated when I push and then have to go back and rework my history.

**Describe the solution you'd like**
Git doesnt event let me commit changes.

**Describe alternatives you've considered**
Vacations?

**Additional context**
Add any other context about the feature request here.

**Requester Info**
Sam Price

**Comment by chillfig** [comment]
CCB 27 October 2022: Agreed to close without merging .git/hooks. Best to configure on the developer's local git instance.
