### ISSUE TITLE
Consider moving cpu usage code to OSAL

### ISSUE THREAD

**Issue by skliper** [nasa/osal#228]
Currently, code to request cpu usage is included in the HS application.  However, this requires HS to be modified to run on different operating systems.  Because the code to request cpu usage is OS-specific, consider moving this functionality out of HS to the OSAL.

**Comment by skliper** [comment]
_Imported from trac issue 205.  Created by ejtimmon on 2018-11-13T17:36:17, last modified: 2019-08-14T14:11:46_

**Comment by dmknutsen** [comment]
Closing because the CPU usage has been successfully integrated into the PSP
