### ISSUE TITLE
PTHREAD_STACK_MIN typo in POSIX/POSIX-NG OSAL

### ISSUE THREAD

**Issue by skliper** [nasa/osal#232]
Both the POSIX and POSIX-NG OSALs contain the following in `osapi.c`:
{{{#!c
#ifndef PTHREAD_STACK_MIN
   #define PTHREAD_STACK_MIN 8092
#endif
}}}

I believe this is supposed to be 8192 or 8*1024.

**Comment by skliper** [comment]
_Imported from trac issue 209.  Created by tflemin1 on 2019-03-28T14:41:32, last modified: 2019-08-14T14:11:46_

**Comment by davearch** [comment]
Hello, can I fix this issue? Seems simple enough

**Comment by skliper** [comment]
@davearch Absolutely!  Note we need one of the following to cover "external contributions" (there's also a link on the pull request template, submission instructions on the form):
https://github.com/nasa/osal/blob/master/doc/GSC_18370_Corp_CLA_form_1219.pdf
https://github.com/nasa/osal/blob/master/doc/GSC_18370_Ind_CLA_form_1219.pdf

**Comment by davearch** [comment]
@skliper Thank you so much! So to be clear, I should fill out the individual contributor form and mail it in before I submit a pull request?

**Comment by davearch** [comment]
Oh I just saw I can email it I will do that

**Comment by skliper** [comment]
@davearch email is preferred.  Order isn't all that critical, we just mark a pull request as needs CLA until we can confirm it has been received.  Individual is the right form as long as you are doing it on your time.  Corporate form is for contributions done as part of your job.
