### ISSUE TITLE
Move OS_FS_ERR_* defines to common os error definitions

### ISSUE THREAD

**Issue by skliper** [nasa/osal#262]
OS_DirectoryOpen returns OS_INVALID_POINTER if dir_id or path pointers are NULL.

OS_DirectoryRead returns OS_FS_ERR_INVALID_POINTER if dirent pointer is NULL.

Likely other cases of mixed use.  Suggest deprecation of the OS_FS_ERR_* defines and switch to common definitions.

**Comment by skliper** [comment]
_Imported from trac issue 239.  Created by jhageman on 2019-08-23T14:59:31, last modified: 2019-08-23T14:59:31_

**Comment by skliper** [comment]
Related to #118.  Really should deprecate the OS_FS_* defines that aren't unique to FS.

**Comment by ejtimmon** [comment]
A handful of apps use OS_FS_SUCCESS and/or OS_FS_ERROR.
