### ISSUE TITLE
doxygen warning: expected <tr>

### ISSUE THREAD

**Issue by avan989** [nasa/osal#279]
**Describe the bug**
doxygen is giving warning: expected <tr> tag but found TK_LNKWORD token instead!

[userguide_osal_expected_tr_warning.txt](https://github.com/nasa/osal/files/3789109/userguide_osal_expected_tr_warning.txt)

**To Reproduce**
1. make usersguide
2. see warning in build/doc

**System observed on:**
 - Hardware
 - Ubuntu 18.04
 - r.c-6.7.0

**Reporter Info**
Anh Van, NASA Goddard

**Comment by skliper** [comment]
Closed by #371
