### ISSUE TITLE
cppcheck coverage check warning

### ISSUE THREAD

**Issue by avan989** [nasa/osal#287]
**Describe the bug**
reference issue #283 

[osal/src/os/posix/osapi.c:1832]: (error) Shifting signed 32-bit value by 31 bits is undefined behaviour
[osal/src/unit-test-coverage/shared/src/coveragetest-time.c:175]: (error) Shifting signed 32-bit value by 31 bits is undefined behaviour
[osal/src/unit-test-coverage/shared/src/coveragetest-timebase.c:111]: (error) Shifting signed 32-bit value by 31 bits is undefined behaviour
[osal/src/unit-test-coverage/ut-stubs/src/libc-stdio-stubs.c:145]: (error) Uninitialized variable: actual
[osal/src/unit-test-coverage/ut-stubs/src/libc-stdio-stubs.c:167]: (error) Uninitialized variable: actual

**Reporter Info**
Anh Van, NASA Goddard

**Comment by skliper** [comment]
@jphickey Anh split the ticket, let me know if you foresee any challenges in getting this resolved quickly.

**Comment by skliper** [comment]
@jphickey will you be able to address this one soon or should I reassign?  It's a hold on us enforcing no cppcheck errors in CI.
