### ISSUE TITLE
doxygen illegeal command

### ISSUE THREAD

**Issue by avan989** [nasa/osal#289]
**Describe the bug**
cfecmdmnems:6: warning: Illegal command \dd as the argument of a \dd command ....
....
cfetlmmnems:211: warning: Illegal command \SB_PIPEOPTSEC as the argument of a \c command

**To Reproduce**
1. make usersguide

**System observed on:**
 - Hardware
 - Ubuntu 18.04
 - doxygen 1.8.13

**Reporter Info**
Anh Van, NASA Goddard

**Comment by skliper** [comment]
Closed by #371
