### ISSUE TITLE
Remove unsupported/untested BSPs

### ISSUE THREAD

**Issue by skliper** [nasa/osal#307]
**Is your feature request related to a problem? Please describe.**
Old BSPs are not within scope of the cFS framework and not tested

**Describe the solution you'd like**
Remove sis-rtems, mcf5235-rtems, and sparc-vxworks6.7

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
While we are at it can we also rename the `genppc-vxworks6.4` bsp to be `mcp750-vxworks`, like the PSP?

Note that although the actual startup code is very generic, the volume table (in `bsp_voltab.c`) is fairly board-specific.

**Comment by skliper** [comment]
Makes sense to me
