### ISSUE TITLE
lgtm warning - misc. 

### ISSUE THREAD

**Issue by avan989** [nasa/osal#329]
**Describe the bug**
reference issues #320 

posix/osfileapi.c

```
line 186:
execl(shell, "sh", "-c", Cmd, NULL); /* does not return if successful */
--
  | The value of this argument may come from call to getenv and is being passed to execl
```

**Reporter Info**
Anh Van, NASA Goddard

**Comment by avan989** [comment]
Moved osapi-filesys.c, and os-impl-posix-files.c to separate issue.

**Comment by skliper** [comment]
This is a significant security concern.  Suggestion is to separate out the shell functionality and make it optionally included (preference is per build system option).  Or remove shell functionality entirely.

Related to https://github.com/nasa/cFE/issues/84

**Comment by skliper** [comment]
CCB 20190108 - see comment on #332, will move forward with current pull request and consider separation/optional inclusion in the future.
