### ISSUE TITLE
Remove classic build artifacts

### ISSUE THREAD

**Issue by skliper** [nasa/osal#339]
**Is your feature request related to a problem? Please describe.**
Classic build no longer supported.

**Describe the solution you'd like**
Remove all associated artifacts: build directory, all *.mak directories, setvars.sh

**Describe alternatives you've considered**
None

**Additional context**
Makes #164 obsolete

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by avan989** [comment]
I can do this.

**Comment by CDKnightNASA** [comment]
Build instructions in doc/OSAL-Configuration-Guide.doc and .pdf have instructions for classic build. Also the section on building the unit tests requires use of the classic build. A new section needs to be written for building unit tests under cmake and the old classic build section needs to be removed (and refs to the classic build in the cmake section need to be stricken.)

**Comment by skliper** [comment]
Preference is to open a new issue, see #384
