### ISSUE TITLE
os-impl-bsd-sockets.c lgtm warning

### ISSUE THREAD

**Issue by avan989** [nasa/osal#343]
**Is your feature request related to a problem? Please describe.**
References https://github.com/nasa/osal/issues/328 and pull request https://github.com/nasa/osal/pull/330

os-impl-bsd-sockets.c

```
line 217, 568:
if (addrlen == 0 \|\| addrlen > OS_SOCKADDR_MAX_LEN)
--
  | Comparison is always false because addrlen <= 28.
```

**Describe the solution you'd like**
Use
CompileTimeAssert(sizeof(sockaddr_in) <= OS_SOCKADDR_MAX_LEN, AddrLenExceedSockaddrLen)  at the top of file or in header.

**Describe alternatives you've considered**
Leave it as it is. 

**Requester Info**
Anh Van, NASA Goddard

**Comment by skliper** [comment]
Warning no longer triggered, closing.
