### ISSUE TITLE
OS_SocketAccept fails

### ISSUE THREAD

**Issue by CDKnightNASA** [nasa/osal#349]
**Describe the bug**
When using OS_SocketAccept on a stream (TCP) server socket, it fails because the accept code calls OS_ObjectIdGetById() passing a OS_LOCK_MODE_REFCOUNT, but then OS_SocketAccept sees the refcount > 0 and fails out.

**To Reproduce**
Create code (e.g. an app) that creates a TCP socket server and try using OS_SocketAccept() to receive the incoming connections.

**Expected behavior**
OS_SocketAccept should work as expected/documented.

**Code snips**
OS_SockAddr_t Addr;
int Socket = 0, ClientFd;
int32 Status = 0;

OS_SocketAddrInit(&Addr, OS_SocketDomain_INET);
OS_SocketAddrFromString(Addr, "127.0.0.1");
OS_SocketOpen(&Socket, OS_SocketDomain_INET, OS_SocketType_STREAM);
OS_SocketBind(Socket, &Addr);
Status = OS_SocketAccept(Socket, &ClientFd, &Addr, 0);

**System observed on:**
Debian 9 64-bit x86

**Additional context**
removing the check for refcount results in expected behavior, OS accept() call should be thread-safe so need not maintain lock through SocketAccept() function.

**Reporter Info**
Chris Knight, NASA Ames

**Comment by skliper** [comment]
Is it possible to create a functional test case to cover this?  The fact it doesn't work seems to indicate a missing functional test.

**Comment by skliper** [comment]
@CDKnightNASA - any progress on this one?  Do you suggest we discuss at a CCB, or is there anything you need to help resolve it?

**Comment by CDKnightNASA** [comment]
I need to write unit tests for it, hasn't been high on priority list. I can take a crack at it today.

**Comment by CDKnightNASA** [comment]
FYI @jphickey there's a great dearth of unit tests for the network API...

So I wasn't clear after this last CCB whether we should use stubbed versions of the OS calls or use the real calls in unit testing. I am guessing that socket code should call the stubs as the OS may throw errors depending on firewall or other security-related configuration.

**Comment by CDKnightNASA** [comment]
see #373
