### ISSUE TITLE
Remove FPU and exception handling APIs from OSAL

### ISSUE THREAD

**Issue by skliper** [nasa/osal#366]
**Is your feature request related to a problem? Please describe.**
Exception and FPU exception handling only partially implemented in OSAL

**Describe the solution you'd like**
Remove from OSAL, better suited to PSP if/when fully implemented.

**Describe alternatives you've considered**
None

**Additional context**
See also #18 to remove shared memory APIs

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by skliper** [comment]
Note FPUExecAttachHandler, FPUExcEnable and FPUExcDisable also don't have functional tests.  Certification issue

**Comment by astrogeco** [comment]
CCB 2020-03-25: No objections

**Comment by jphickey** [comment]
Note that these functions are being called by `src/unit-tests/oscore-test/ut_oscore_exception_test.c`.  As part of PR #427 I was testing by removing the FPU functions and got a link failure about this.  Will need to reconcile somehow.

I thought this was CCB approved but it looks like it hasn't been merged to master yet.  Is this waiting on anything?

**Comment by skliper** [comment]
@jphickey that test was removed in #415?  @astrogeco hasn't merged yet.

**Comment by jphickey** [comment]
That may explain it - I thought it was merged already.  Nonetheless in order for PR #427 to work with `OMIT_DEPRECATED` set then this is needed, so will need to rebase after this is merged.
