### ISSUE TITLE
Object Utility API's missing functional test

### ISSUE THREAD

**Issue by skliper** [nasa/osal#374]
**Is your feature request related to a problem? Please describe.**
OS_IdentifyObject, OS_ConvertToArrayIndex and OS_ForEachObject missing explicit functional tests

**Describe the solution you'd like**
Add tests

**Describe alternatives you've considered**
None.

**Additional context**
Certification violation

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by yammajamma** [comment]
I can take this one.

**Comment by skliper** [comment]
Recommend following the osal/src/tests model.  Concept is to demonstrate these functionally work as intended/specified in the API (black box).  You can find the API here: https://github.com/nasa/cFS/blob/gh-pages/OSAL_Users_Guide.pdf
