### ISSUE TITLE
OS_IntGetMask OS_IntSetMask missing functional tests

### ISSUE THREAD

**Issue by skliper** [nasa/osal#376]
**Is your feature request related to a problem? Please describe.**
Missing functional tests for OS_IntGetMask and OS_IntSetMask

**Describe the solution you'd like**
Add tests

**Describe alternatives you've considered**
None

**Additional context**
Certification issue

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
Not so sure how these can be tested in a functional test as the definition of an interrupt mask is CPU/BSP-specific.  While OSAL might have a wrapper around the syscall it doesn't really abstract the semantics of it.  Furthermore, the side effects are likely quite different on a multi-core CPU.

Recommend to deprecate the functions, like the FPU variants.  I don't see either of these calls being used by any current CFE/PSP code.  POSIX and RTEMS both return `OS_ERR_NOT_IMPLEMENTED` for these anyway.

**Comment by skliper** [comment]
@acudmore opinion?  I'm all for deprecation.

**Comment by skliper** [comment]
#71 also related (and highlights issue of platform dependence).

**Comment by skliper** [comment]
#396 makes this no longer applicable
