### ISSUE TITLE
Deprecate OS_Int* related APIs

### ISSUE THREAD

**Issue by skliper** [nasa/osal#385]
**Is your feature request related to a problem? Please describe.**
Interrupt abstraction is platform/CPU dependent, and better suited to the PSP if needed as indicated by the partial implementation in OSAL, the related issues, and lack of functional tests at the OSAL level.

**Describe the solution you'd like**
Deprecate

**Describe alternatives you've considered**
None

**Additional context**
See #370, #376, #71

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by astrogeco** [comment]
CCB 2020-03-25: No objections
