### ISSUE TITLE
OS_SelectFdZero/OS_SelectFdAdd/OS_SelectFdClear/OS_SelectFdIsSet does not ensure Set is != NULL

### ISSUE THREAD

**Issue by CDKnightNASA** [nasa/osal#390]
**Describe the bug**
Users of these API's will cause a seg fault if they call these functions with a null pointer.

**To Reproduce**
Call OS_SelectFdZero(NULL), etc.

**Expected behavior**
These API's should return an error code when provided a NULL pointer.

**Code snips**
```
int32 OS_SelectFdZero(OS_FdSet *Set)
{  
   memset(Set,0,sizeof(OS_FdSet));
   return OS_SUCCESS;
} /* end OS_SelectFdZero */
```

**System observed on:**
Debian 9

**Additional context**

**Reporter Info**
Christopher.D.Knight@nasa.gov

**Comment by astrogeco** [comment]
CCB 2020-04-01 - Discussed, approved implementation as long as it doesn't change API.
