### ISSUE TITLE
Add reference to OSAL user's guide from README.md

### ISSUE THREAD

**Issue by skliper** [nasa/osal#413]
**Is your feature request related to a problem? Please describe.**
User's guide is built and not included in repo

**Describe the solution you'd like**
Reference https://github.com/nasa/cFS/blob/gh-pages/OSAL_Users_Guide.pdf

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by yammajamma** [comment]
I can take this issue.  ~Yasir
