### ISSUE TITLE
Test_OS_ConvertToArrayIndex: tautological assertion

### ISSUE THREAD

**Issue by lethuillierg** [nasa/osal#425]
**Describe the bug**
Unit test ` Test_OS_ConvertToArrayIndex` implements the following assertion: 
https://github.com/nasa/osal/blob/7d9c4c8a470d3906050c5cf93203c4a9a9c09089/src/unit-test-coverage/shared/src/coveragetest-idmap.c#L610-L611

This is a tautological assertion as it compares `local_idx1` with itself.

**To Reproduce**
N/A (code analysis)

**Expected behavior**
`local_idx1` should be compared with `local_idx2`:
```
UtAssert_True(local_idx1 == local_idx2, "local_idx1 (%lu) == local_idx2 (%lu)",
            (unsigned long)local_idx1, (unsigned long)local_idx2);
```

**Code snips**
See above.

**System observed on:**
N/A (code analysis)

**Additional context**
N/A

**Reporter Info**
Guillaume Lethuillier - Personal

**Comment by skliper** [comment]
@yammajamma - want to take this one?

**Comment by yammajamma** [comment]
@skliper Yes!
