### ISSUE TITLE
Simplify config by inferring OSAL_SYSTEM_OSTYPE from OSAL_SYSTEM_BSPTYPE

### ISSUE THREAD

**Issue by jphickey** [nasa/osal#432]
**Is your feature request related to a problem? Please describe.**
Currently the build requires that the user specify both OSAL_SYSTEM_BSPTYPE and OSAL_SYSTEM_OSTYPE.  This is redundant because each BSP only works with a specific OS.  

**Describe the solution you'd like**
The user should be allowed to specify only OSAL_SYSTEM_BSPTYPE, and the correct OS layer can be inferred automatically.

**Describe alternatives you've considered**
Continue as is, which increases user config burden and risk of misconfiguration

**Additional context**
see also nasa/cfe#632

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by astrogeco** [comment]
CCB 20200422 - Open new PR for 2f67435fe320769dfdea1f129f738fb94fbe3bbe and fast track
