### ISSUE TITLE
Deprecate OStask_id field from OS_task_prop_t

### ISSUE THREAD

**Issue by jphickey** [nasa/osal#437]
**Is your feature request related to a problem? Please describe.**
This field is not necessarily applicable to all OS types and it breaks the abstraction.  OSAL should not be reporting the raw/unabstracted values back to the application.

This field is fundamentally broken in any environment where the underlying OS task ID isn't convertible to a `uint32`.  This includes real systems, such as:

- Cygwin, where `pthread_t` is a compound data type, not an integer (POSIX specifically allows this)
- Systems where the task ID is actually pointer to the TCB (in which case it will be 64 bits on 64 bit systems)

Currently this field serves one purpose, which is to allow the CFE ES exception processing to find the OSAL task ID associated with the exception.   However, this design is being reworked in nasa/cfe#411 where more of the exception processing is done in the CFE PSP.  With this, there should be no need for applications to ever use the `OStask_id` member.

**Describe the solution you'd like**
The `OStask_id` member of `OS_task_prop_t` should be marked as deprecated.  As a replacement, an new API can be added which can be invoked by the PSP/BSP to aid in exception processing.  This new API should use an abstract pointer and size, not assume that the task identifier information fits within a 32-bit integer.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by jphickey** [comment]
@skliper, @acudmore, @jwilmot - please comment if you have any thoughts on this, I'd like to include this as part of the overall strategy for fixing nasa/cfe#411 and nasa/cfe#76.

**Comment by skliper** [comment]
Concur.

**Comment by acudmore** [comment]
The proposed solution sounds good to me.
