### ISSUE TITLE
Order of operations on OS_DeleteAllObjects

### ISSUE THREAD

**Issue by jphickey** [nasa/osal#471]
**Is your feature request related to a problem? Please describe.**
OS_DeleteAllObjects() is used when shutting down the system, such as after an exception, a commanded processor restart, or CTRL+C, etc.

This simply deletes resources based on their numeric `OS_OBJECT_TYPE` value, meaning tasks (1) are first, followed by queues, bin/count, semaphores, mutexes, etc. and eventually timers (9).

A recent issue described in nasa/cfe#701 observed a potential problem with this.  As the task and semaphore are deleted, a timer could still be running.  If that timer executes during shutdown, it may interrupt the deletion, and attempt to use semaphore objects.

Normally this shouldn't be an issue because OSAL will return an error and reject the call.  However due to an underlying issue in Binary Semaphores (#470) after task cancellation, this caused deadlock.

**Describe the solution you'd like**
It would be preferable to delete timers first, then tasks, then semaphores, files, and other resources.  This should be a safer ordering in general, as it will reduce the potential for resources to be used as they are being deleted.

**Describe alternatives you've considered**
Leave as-is.  

**Additional context**
The real fix for #470 prevents deadlock, this is just more future-proofing.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by CDKnightNASA** [comment]
It wouldn't hurt to also delete objects in reverse order...For short-lived instances they will likely be in reverse order (eldest first). Of course this is no guarantee, but easy to implement in the code.

**Comment by skliper** [comment]
@jphickey want to resolve this for Caelum?

**Comment by jphickey** [comment]
Sure, I think I already have a patch for this somewhere that never got put into a final PR.  I can find it and submit.
