### ISSUE TITLE
file descriptor signed or unsigned?

### ISSUE THREAD

**Issue by CDKnightNASA** [nasa/osal#498]
**Describe the bug**
OS_Open() returns an int32 file descriptor, OS_SocketAccept() takes a uint32 pointer for the file descriptor. They should be the same type. (The socket code should probably use/take int32.)

**Reporter Info**
Christopher.D.Knight@nasa.gov

**Comment by skliper** [comment]
The old APIs have been removed, so this is no longer relevant (marking resolved by #617).
