### ISSUE TITLE
OS_FPUExcSetMask and OS_FPUExcGetMask VxWorks OSAL unit tests fail

### ISSUE THREAD

**Issue by mbenson1** [nasa/osal#530]
**Describe the bug**
The VxWorks OSAL unit tests for OS_FPUExcSetMask and OS_FPUExcGetMask are CPU specific, not just OS specific.  These functions have conditionally compiled code that is conditional on whether or not the platform is the PPC440, but the unit test code does not.

**Expected behavior**
The unit test should pass, though I'm unsure whether the break is in the OSAL or the unit test code.

**System observed on:**
 - AiTech SP0-S
 - OS: VxWorks 6.9
 - OSAL 5.0.3-bv

**Reporter Info**
Mathew Benson
Windhover Labs

**Comment by skliper** [comment]
Fixed in #415.
