### ISSUE TITLE
Set posix thread names using task name when creating CFE tasks

### ISSUE THREAD

**Issue by dsburns** [nasa/osal#532]
**Is your feature request related to a problem? Please describe.**
It would be helpful for the pthread name to match the CFE task name in the underlying OS on POSIX platforms.  This would allow for a better user experience when debugging CFE applications using Linux based utilities i.e. strace, htop, etc.

**Describe the solution you'd like**
This can be accomplished by using the _pthread_setname_np_ function in the _OS_Posix_InternalTaskCreate_Impl_ function.  Since this is a non-posix function, each BSP can specify the availability of this function through a #define in osconfig.h

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Dan Burns (GSFC - 596.0)
daniel.s.burns@nasa.gov

**Comment by astrogeco** [comment]
@dsburns take a look at #541 that we just merged.

**Comment by skliper** [comment]
And I think @jphickey is planning to submit a PR to the PSP to set the thread names using this mechanism.

**Comment by jphickey** [comment]
> And I think @jphickey is planning to submit a PR to the PSP to set the thread names using capability implemented in #541.

Done - see nasa/psp#199.

**Comment by skliper** [comment]
Closing as duplicate, actually implemented in PSP (nasa/PSP#199)
