### ISSUE TITLE
Overall Tests Pass Even With a TSF

### ISSUE THREAD

**Issue by yammajamma** [nasa/osal#537]
**Describe the bug**
The software is set up such that overall tests pass even if there is a test case that TSF.  I have had individual TSFs, and yet the overall tests showed everything passed.  

See code here: https://github.com/nasa/osal/blob/80fdd67a6c28a962164697ece12570142331ea44/ut_assert/src/utbsp.c#L213

**System observed on:**
cFS Dev Server
OS: Ubuntu 18.04
Versions: OSAL 5.0.11.0

**Reporter Info**
Yasir Majeed Khan
NASA GSFC/Emergent Space

**Comment by skliper** [comment]
Yeah, I've run into two cases in cFE with TSF... probably should count these as CI failures.
