### ISSUE TITLE
VxWorks OS_CountSemCreate unit test fails

### ISSUE THREAD

**Issue by mbenson1** [nasa/osal#542]
**Describe the bug**
The OS_CountSemCreate unit test, "#4 Initial-count-too-high", fails.  This is because the vxworks OSAL, as written, does not check the initial count.  Rather, it passes it directly to the OS call.

**Expected behavior**
It should pass.

**System observed on:**
 - AiTech SP0-S 
 - OS: VxWorks 6.9
 - OSAL 5.0.3-bv

**Reporter Info**
Mathew Benson
Windhover Labs

**Comment by jphickey** [comment]
Just checked into this - and it is probably related to the value of `SEM_VALUE_MAX`

The test is supposed to be skipped as "NA" if the system doesn't define a specific maximum, but an issue would occur if the `SEM_VALUE_MAX` was actually defined as value 0xFFFFFFFF - in this case it would wrap and therefore pass 0, and the test wouldn't work properly.

**Comment by jphickey** [comment]
@mbenson1 can you confirm if your platform defines a `SEM_VALUE_MAX` macro and if so, what is the actual value?

**Comment by skliper** [comment]
Pushed a potential fix (#681). @mbenson1 can you confirm this solves the issue?  If not we will need more information to resolve.
