### ISSUE TITLE
DATAGRAM Network Function OS_SocketSendTo Segfault

### ISSUE THREAD

**Issue by yammajamma** [nasa/osal#544]
**Describe the bug**
OS_SocketSendTo() Segfaults when passed in NULL for Remote Address (last parameter) and all the other parameters are valid.

**System observed on:**
cFS Dev Server
OS: Ubuntu 18.04
Versions: OSAL 5.0.11.0

**Reporter Info**
Yasir Majeed Khan
NASA GSFC/Emergent Space

**Comment by skliper** [comment]
Relates to nasa/cfe#520, would be helpful to have the run time assert to check for null pointer.
