### ISSUE TITLE
Documentation Updates

### ISSUE THREAD

**Issue by yammajamma** [nasa/osal#545]
**Describe the bug**
1. In osapi-os-net.h, OS_SocketAccept lists addr as an [in] parameter where as it is an [out] parameter.  This is where a new connection's incoming address is stored as an output to the function call and is not an input to the function.
(File location: osal/src/os/inc/osapi-os-net.h)

2. In osapi-os-core.h, OS_TaskCreate notates  the input parameter "stack_size" as "stack_size: the size of the stack, or 0 to use a default stack size".   A 0 input here is not valid and should be appointed an appropriate stack size.  
(File location: osal/src/os/inc/osapi-os-core.h)

3. In osapi-os-filesys.h, OS_TimedRead/OS_TimedWrite.  While the documentation is clear that these functions are used primarily with sockets, it is unclear how a socket may be used as an input parameter.  The first input parameter "filedes" is notated as "The handle ID to operate on" but I think it would be prudent to add an additional comment to explain that this is also the socket ID.  Perhaps these two functions should also be defined with the rest of the network functions in (osal/src/os/inc/osapi-os-net.h) instead of with functions used for file operations (osal/src/os/inc/osapi-os-filesys.h) for further specified use and clarity.  It was not easily clear on how to send messages back and forth between a STREAM connection, as it is with DATAGRAM connections.
(File location: osal/src/os/inc/osapi-os-filesys.h)

**System observed on:**
cFS Dev Server
OS: Ubuntu 18.04
Versions: OSAL 5.0.11.0

**Additional context**

**Reporter Info**
Yasir Majeed Khan
NASA GSFC/Emergent Space

**Comment by jphickey** [comment]
Looking back at existing issues, looks like 1 and 3 above were addressed by my recent PR #972, which fixes docs on OS_SocketAccept and OS_TimedRead/Write.

Only thing left here is to fix the stack size item (2).
