### ISSUE TITLE
OSAL should provide a typedef for "ID" values

### ISSUE THREAD

**Issue by jphickey** [nasa/osal#555]
**Is your feature request related to a problem? Please describe.**
The OSAL API uses `uint32` type to identify objects/resources in an abstract way.

**Describe the solution you'd like**
There should be a typedef for this.  For instance:

    typedef uint32 OS_id_t;

This typedef can then be used in all APIs rather than using `uint32` directly.

**Describe alternatives you've considered**
Keep using `uint32`.

**Additional context**
Providing a typedef is generally accepted as good practice in terms of future proofing the code.  This wouldn't change anything immediately, as the type will remain `uint32` as it currently is.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by jphickey** [comment]
Ping @skliper , @acudmore --

Stuff I'm working in CFE made me think of this - we are using `uint32` directly in the OSAL API for ID values.  Do you think a typedef is worthwhile to squeeze into the current release before the window closes?  Probably wouldn't be hard to do, just a matter of scrubbing the prototypes/declarations in the API to use the typedef.  Functionality wouldn't change as long as we keep it a `uint32` underneath...

**Comment by skliper** [comment]
You mean "Caelum"?  If so, yes, that makes sense to me.
