### ISSUE TITLE
Adding unit tests from with a unit test not a supported pattern

### ISSUE THREAD

**Issue by skliper** [nasa/osal#577]
**Describe the bug**
Possibly related to #554 (reverted to v5.1.0-rc1 and they ran).  Adding tests after starting to run tests (adding a test within a test) is not a supported pattern, and they won't actually get run (they do get added to the front of the individual list, but the merged test list doesn't not handle them).

**To Reproduce**
Add a unit test from within a unit test, build/execute and the added unit test will not execute.

**Expected behavior**
Didn't know NOT to do this... just don't do it.

**Resolution**
Just don't do it.
Document limitations and proper usage.

**Code snips**
uttest.c - see the adding and merging

**System observed on:**
 - Hardware: cFS Dev Server
 - OS: Ubuntu 18.04
 - Versions checked latest integration candidate and v5.1.0-rc1, problem does not exist in v5.1.0-rc1

**Additional context**
#554 

**Reporter Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
I just checked for SB in the `main` branch and they seem to work there....

**Comment by skliper** [comment]
Looks like it's not due to #554.  Try the bundle `integration-candidate`, the `sb` subtests don't look like they execute.

**Comment by skliper** [comment]
Starting to look like nasa/cFE#726 may have broken it... still digging in.

**Comment by skliper** [comment]
Looks like ut_assert now silently fails to add a test from inside another test.  This worked pre #554.  `sb` didn't do this, but `msg` did.

**Comment by skliper** [comment]
Or I should probably say doesn't add the test in a way that it will get executed, since it gets added to the front of the list (at least that's what it looks like on quick inspection.)

**Comment by jphickey** [comment]
Ahh yes, that would explain it - because that happens after combining the setup+test+teardown lists into one summary list, the newly-added test is still sitting on one of the component lists, not the summary list.

If this is a desired/necessary feature (to add tests during tests) then perhaps we can add an outer loop into UtTest_Run to pick up tests that been added during the run.  Would be simple to add.

**Comment by skliper** [comment]
@astrogeco - can we close this?  No requirement or real use case identified... just don't add test cases from other test cases.  No need to implement additional logic simply to add complexity.
