### ISSUE TITLE
Add support for RTEMS 5.1 - RTEMS OSAL and pc-rtems OSAL BSP updates

### ISSUE THREAD

**Issue by acudmore** [nasa/osal#608]
**Is your feature request related to a problem? Please describe.**
The cFS Bundle currently supports RTEMS 4.11. Now that RTEMS 5.1 has been released, I would like to update the necessary components to support RTEMS 5.1 on the pc-rtems platform. This involves minor modifications to the cfe repository, the PSP repository, and the OSAL repository. These changes can be done in such a way that preserves the current RTEMS 4.11 support and adds RTEMS 5.1 support.

**Describe the solution you'd like**
I would like to add support for RTEMS 5.1 while maintaining compatibility with the existing RTEMS 4.11 support. For the OSAL repository there are a few minor changes needed to allow support of RTEMS 5.1 and RTEMS 4.11:
- Minor changes in the OSAL pc-rtems BSP
- Minor changes in the RTEMS OSAL implementation files

**Describe alternatives you've considered**
Alternatives include:
- Not supporting newer versions of RTEMS, but several projects will depend on RTEMS 5 support.
- Dropping RTEMS 4.11 support and just making the changes needed for RTEMS 5, but there may be projects that depend on RTEMS 4.11. We can consider dropping RTEMS 4.11 support on a future release.

**Additional context**

**Requester Info**
Alan Cudmore / NASA GSFC Code 582

**Comment by joelsherrill** [comment]
I think I know of one project that used cFS and RTEMS 4.11. Obviously, there could be many others. Whether any cFS users ever update RTEMS or cFS might be an interesting topic. I suspect they select and freeze with no upgrade. The next project may move to a newer version.

If projects are using SMP, I would recommend they move to 5.x.

**Comment by acudmore** [comment]
Related to:
CFE 914: https://github.com/nasa/cFE/issues/914
PSP 197: https://github.com/nasa/PSP/issues/197
