### ISSUE TITLE
Update OSAL Configuration Guide 

### ISSUE THREAD

**Issue by ArielSAdamsNASA** [nasa/osal#611]
**Is your feature request related to a problem? Please describe.**
The [OSAL Configuration Guide](https://github.com/nasa/osal/blob/master/doc/OSAL-Configuration-guide.pdf) is out of date. More specifically, I found in section 2.1.1, Setup the OSAL Source Distribution, that the OSAL source distribution directories are not aligned with our current directories. For example, osal/src/make and osal/src/inc no longer exists. 

**Describe the solution you'd like**
A new revision should be published. Last revision was on 1/31/2016. 

**Requester Info**
Ariel Adams, ASRC Federal

**Comment by skliper** [comment]
Duplicate of #384
