### ISSUE TITLE
Typo in RTEMS binsem.c Variable Name

### ISSUE THREAD

**Issue by adam-stamand** [nasa/osal#613]
https://github.com/nasa/osal/blob/27c24693c02b3800e8c95a5b6a44cb1c56451b6b/src/os/rtems/src/os-impl-binsem.c#L249

I believe the line is meant to read the following:

`if (OS_Milli2Ticks(msecs, &TimeInTicks) != OS_SUCCESS)`

**Comment by skliper** [comment]
Yup, good catch.

**Comment by astrogeco** [comment]
Fixed in #616
