### ISSUE TITLE
FreeRTOS port

### ISSUE THREAD

**Issue by jonathanmichel** [nasa/osal#620]
Hi,

It seems that you only provide the OSAL for Linux, rtems and vxworks. However you regularly mention FreeRTOS in your documentation. Do you plan to share the sources for the FreeRTOS port ? Not sure the amount of work such operation require and the limitations (especially concerning the file system) . It would be great to have more information about this point. 

Thanks in advance !

**Requester Info**
Jonathan Michel, master student at the University of Applied Science of Western Switzerland working on [CHESS](https://www.epflspacecraftteam.com/).

**Comment by skliper** [comment]
Hi Jonathan - the best resource for OSAL implementations that are not provided as part of the cFS Framework is the community email list.  FreeRTOS is occasionally a topic on that list, and there are a few related community efforts that are likely much more up-to-date (as of last year it looks like they were targeting FreeRTOS 10) than anything I have access to.  The subscription request can be found here: https://lists.nasa.gov/mailman/listinfo/cfs-community.

**Comment by skliper** [comment]
Once you are in, the most recent FreeRTOS thread I found was: https://lists.nasa.gov/mailman/private/cfs-community/2019-December/001399.html (access for community members only).

**Comment by jonathanmichel** [comment]
Thanks I will take a look. I subscribed to the community and am waiting for the confirmation for now.

**Comment by jonathanmichel** [comment]
@skliper Is the [email list website](https://lists.nasa.gov/mailman/listinfo/cfs-community) down on your side too ?

**Comment by skliper** [comment]
@jonathanmichel Just tested and I am able to sign in and get to the archives

**Comment by jonathanmichel** [comment]
@skliper Strange. It was working yesterday but I never received the email confirmation. And today the website is down (ERR_CONNECTION_TIMED_OUT on my computer and ERR_CONNECTION_TIMED_RESET on my mobile phone). Do you have any idea ?

**Comment by skliper** [comment]
@jonathanmichel contact me via email and I'll see what I can do.  Any pull request I have submitted will have a commit w/ my email in it.

**Comment by aogrcs** [comment]
@skliper 
Dear,
I found that I could not open this site, thanks

**Comment by skliper** [comment]
@aogrcs - you need to join the community email list at https://lists.nasa.gov/mailman/listinfo/cfs-community prior to being able to view the archives.

**Comment by aogrcs** [comment]
@skliper,
Is the website down for country outside US? Thanks

**Comment by skliper** [comment]
@aogrcs - good question.  If the links above for the community email list don't work, you could try the contact information associated with top results on a search (https://www.google.com/search?q=cfs+freertos).  FreeRTOS isn't officially supported from nasa/OSAL, but there are ports the wider community have developed.

**Comment by aogrcs** [comment]
@skliper maybe I should do it myself, thanks

**Comment by PratikAher20** [comment]
> @skliper Strange. It was working yesterday but I never received the email confirmation. And today the website is down (ERR_CONNECTION_TIMED_OUT on my computer and ERR_CONNECTION_TIMED_RESET on my mobile phone). Do you have any idea ?
Facing the same problem... Please Help

**Comment by skliper** [comment]
Hi @PratikAher20, @dzbaker @dmknutsen are the prime contacts these days for cFS.
