### ISSUE TITLE
OS_chmod missing functional test

### ISSUE THREAD

**Issue by skliper** [nasa/osal#631]
**Is your feature request related to a problem? Please describe.**
Missing functional test (coverage test exists).

**Describe the solution you'd like**
Add functional test

**Describe alternatives you've considered**
None

**Additional context**
Required for cert

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by zanzaben** [comment]
Talked with @jphickey and mentioned how OS_chmod doesn't work on some operating systems so any added tests have to account for that.
