### ISSUE TITLE
More consistent types for OSAL resources

### ISSUE THREAD

**Issue by jphickey** [nasa/osal#635]
**Is your feature request related to a problem? Please describe.**
CFE issue nasa/cfe#663 describes mismatched types used across CFE for certain items, such as stack size and priority of tasks.
To help resolve this OSAL should provide a typedef for the "right" types to use when interfacing with OSAL.

**Describe the solution you'd like**
Should add at least:
- `osal_priority_t` - type used for OSAL task priority
- `osal_stackptr_t` - type used for OSAL stack pointer

**Additional context**
This will identify the correct type to use, instead of the mishmash currently seen in CFE as described in nasa/cfe#663.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by jphickey** [comment]
Question for @skliper and @acudmore --- OSAL also (still) uses `uint32` for size everywhere.  We already have a typedef for `cpusize` aka `size_t` - should I also update the OSAL APIs to use `cpusize` instead of `uint32` in the APIs that accept a size?

**Comment by jphickey** [comment]
Otherwise I can limit this to only fixing the type used for priority and the stack pointer (which only occur in a couple places).

**Comment by skliper** [comment]
I'm good with the size change also.
