### ISSUE TITLE
OS_TaskDelete is not synchronous on POSIX

### ISSUE THREAD

**Issue by jphickey** [nasa/osal#642]
**Describe the bug**
The current POSIX implementation of `OS_TaskDelete()` uses `pthread_cancel()`.  This is a cancellation _request_ but the target thread continues to run until it hits a cancellation point.  As a result, when the OS_TaskDelete() function returns, it is likely that the target thread is actually still running for a short period of time.

But if the intent is to actually unload the module, as is done in the CFE "restart" and "reload" commands, it is critical to ensure that all uses/references to code within the to-be-unloaded module have actually been released.  So it is important to make sure that the cancellation request has been executed and the task is actually deleted before proceeding to the `OS_ModuleUnload()` call.

Currently with the POSIX implementation, there is no way to guarantee this, so this becomes a race condition during restart/reload operations on this platform.

**To Reproduce**
Not directly reproducible in current code - this race condition is currently masked by the fact that modules are loaded with `RTLD_GLOBAL`, so if the runtime loader still sees the module being referenced using its internal refcount, it doesn't actually unload it when `dlclose()` is called.  So in this case the task finishes up normally and there is no apparent problem.

But when this is fixed - such as when using `RTLD_LOCAL` as suggested in #641 - then this race condition becomes a problem, and as a result a CFE reload or restart command sometimes triggers a segmentation fault in the event that `OS_ModuleUnload()` gets called before the task has fully been deleted.

**Expected behavior**
`OS_TaskDelete()` should  ensure that the task has been fully removed, not just pending removal, before it returns to the caller.

Suggestion to achieve this:

- Keep threads in the attached (joinable) state by default
- Use `pthread_join()` to wait for the cancelled task to actually exit.

**System observed on:**
Ubuntu 20.04

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by astrogeco** [comment]
[CCB 2020-11-04](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-November-04-2020)
- Can't fix reload problem without fixing this 
- We have discussed how OS_TaskDelete is dangerous. 
  - Safer using the appropriate flag in POSIX assuming the we do the correct cleanup
  - If app takes a mutex that can't be cancelled we could have issues but we can't control this
- Might need a splinter and further discussion
