### ISSUE TITLE
OS_TaskExit() on VxWorks causes task table owner to be the deleted task

### ISSUE THREAD

**Issue by johnphamngc** [nasa/osal#645]
**Describe the bug**
OS_TaskExit() calls OS_ObjectIdFinalizeDelete(). This function sets  the task's record->active_id to 0, which is also being used as the task ID on VxWorks. ObjectIdFinalizeDelete() subsequently calls OS_Unlock_Global, which errors out and does not clear the owner, as the task ID is now zeroed out and does not match the owner of the table. This does not occur on Linux

**To Reproduce**
On VxWorks, call CFE_ES_ExitChildTask with OSAL_CONFIG_DEBUG_PRINTF  enabled

**Expected behavior**
Error message should not be printed out

**Code snips**
https://github.com/nasa/osal/blob/1a826576f8dd9eb37f47da0e633b1d4712b8ac61/src/os/shared/src/osapi-idmap.c#L745-L777
https://github.com/nasa/osal/blob/1a826576f8dd9eb37f47da0e633b1d4712b8ac61/src/os/shared/src/osapi-idmap.c#L625-L676
https://github.com/nasa/osal/blob/1a826576f8dd9eb37f47da0e633b1d4712b8ac61/src/os/vxworks/src/os-impl-tasks.c#L385-L413
https://github.com/nasa/osal/blob/1a826576f8dd9eb37f47da0e633b1d4712b8ac61/src/os/posix/src/os-impl-tasks.c#L736-L751

**System observed on:**
 - SP0
 - OS: VxWorks 6.9
 - Versions: CFE 6.8, OSAL  5.1.0-rc1+dev16, 

**Additional context**
See attached screenshots for stack traces
![image](https://user-images.githubusercontent.com/63735778/98269251-82b02900-1f5b-11eb-83f9-0af820169aa8.png)
![image](https://user-images.githubusercontent.com/63735778/98269098-5b595c00-1f5b-11eb-836c-4abd911c123e.png)
**Reporter Info**
John N. Pham, Northrop Grumman

**Comment by jphickey** [comment]
Although the tickets don't seem related, what I'm working on for #642 will likely implement a process where the deleted task record is only "marked" as deleted but keeps its ID valid while it waits for the task to actually exit.

So - it should fix this too, because the ID in the global record will still be valid when the unlocking is done.
