### ISSUE TITLE
vxWorks OSAL missing OS_WaitForStateChange_Impl

### ISSUE THREAD

**Issue by klystron78** [nasa/osal#745]
**Describe the bug**
After the merge of vxworks7 support, a rebase was done. It turns out a new required function OS_WaitForStateChange_Impl in the implementation is missing.

**System observed on:**
p5020
vxworks7

**Reporter Info**
Steven Seeger, EFSI, Inc. (GSFC-582)

**Comment by jphickey** [comment]
This is just a baseline issue.  Somehow this vxworks impl got into a separate PR which has been delayed since we haven't done a merge in a while.  This function will exist in the next baseline (PR #704 specifically)
