### ISSUE TITLE
OSC_INUM_TO_IVEC stub returning stack allocated memory

### ISSUE THREAD

**Issue by skliper** [nasa/osal#777]
**Is your feature request related to a problem? Please describe.**
CodeQL warning on line 72 (returning VecTbl):
https://github.com/nasa/osal/blob/09a2c5e793639e508174a2446989274acf36f25e/src/unit-test-coverage/ut-stubs/src/vxworks-intLib-stubs.c#L51-L77

**Describe the solution you'd like**
Make DummyVec static

**Describe alternatives you've considered**
Remove, no longer used in OSAL testing but could be used by PSP implementations.  Leaving in for now.

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by astrogeco** [comment]
>Describe alternatives you've considered
Remove, no longer used in OSAL testing but could be used by PSP implementations. Leaving in for now.

@skliper should we open a separate issue to remove this or port it to PSP?

**Comment by skliper** [comment]
@astrogeco Probably not at this point?  I'm fine w/o for now.  If/when someone needs in a PSP it'll be here/available.

**Comment by astrogeco** [comment]
I'd like having the issue to remove it so we don't forget

**Comment by jphickey** [comment]
> I'd like having the issue to remove it so we don't forget

I think the consensus is _not_ to remove it for now, as it could prove useful again at some point, such as for a VxWorks PSP that does use interrupts.
