### ISSUE TITLE
Convert from strlen to strnlen where appropriate

### ISSUE THREAD

**Issue by skliper** [nasa/osal#808]
**Is your feature request related to a problem? Please describe.**
Per security standards strlen should be avoided if possible:
```
src/os/vxworks/src/os-impl-shell.c:        OS_write(fdCmd, Cmd, strlen(Cmd));
src/os/vxworks/src/os-impl-symtab.c:    if (strlen(name) >= OS_MAX_SYM_LEN)
src/os/shared/src/osapi-sockets.c:        len = strlen(sock->stream_name);
src/os/shared/src/osapi-sockets.c:        len = strlen(sock->stream_name);
src/os/shared/src/osapi-idmap.c:            name_len = strlen(record->name_entry);
src/os/shared/src/osapi-filesys.c:    mplen = strlen(filesys->virtual_mountpt);
src/os/shared/src/osapi-filesys.c:    if (strlen(dev_name) >= OS_FS_DEV_NAME_LEN)
src/os/shared/src/osapi-filesys.c:    VirtPathLen = strlen(VirtualPath);
src/os/shared/src/osapi-filesys.c:    if (strlen(name_ptr) >= OS_MAX_FILE_NAME)
src/os/shared/src/osapi-filesys.c:            SysMountPointLen = strlen(filesys->system_mountpt);
src/os/shared/src/osapi-filesys.c:            VirtPathBegin    = strlen(filesys->virtual_mountpt);
```

**Describe the solution you'd like**
Replace with strnlen where possible.

**Describe alternatives you've considered**
None

**Additional context**
Security analysis warning

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
Unfortunately `strnlen()` is not C99... otherwise would have done this a long time ago!

My recommendation is to use `memchr()` which returns a pointer to the null byte.  If this returns non-null the string pointer can be subtracted which gets the length.  It requires an extra local variable but memchr() is part of ISO C standard so every platform should have this.

**Comment by skliper** [comment]
That's what I get for copy pasting from a security analysis report, suggestion noted!

**Comment by jphickey** [comment]
We could always make an OSAL wrapper around `memchr()` to give ourselves a utility function that works like strnlen does.  That would be easy.  Maybe in `os-common.c` ....   then even other stuff like CFE could use it too.

I can easily see that turning into a dumping ground for "functions the ISO C standard should have but doesn't"
