### ISSUE TITLE
Clean up endian temporary compatibility macro

### ISSUE THREAD

**Issue by skliper** [nasa/osal#843]
**Is your feature request related to a problem? Please describe.**
Missing an else (likely error) case (or !defined(__BYTE_ORDER))
https://github.com/nasa/osal/blob/ead5723f59ee49b36a36d6cb66c4cfe680ebbd68/src/os/inc/common_types.h#L145-L171

It's also a misnomer (BYTE not BIT), and one of many various patterns (see nasa/cFE#1209)

**Describe the solution you'd like**
At minimum add the error case, ideally clean/remove/consolidate.

**Describe alternatives you've considered**
None

**Additional context**
nasa/cFE#1209

**Requester Info**
Jacob Hageman - NASA/GSFC, OSAL code review

**Comment by jphickey** [comment]
Here's the conundrum with this one:

- CFS Developers should be _discouraged_ from writing any endian-specific code.
- So while these macros are defined via some commonly-used C library macros, none of the symbols checked are standardized in any way, nothing is guaranteed to work.
- These BIG/LITTLE macros are only there for backward compatibility.  We don't actually want anyone to use them.  Nothing in OSAL itself uses these at all, either.

SO - at the end of the day - we shouldn't be puting an `#error` in a file that is used _everywhere_ in the event that a (nonstandardized) test was inconclusive as to how to define a macro that we actively discourage you from using.

My recommendation would be to take this out of OSAL completely, and only put it into the CFE file that defines CFE_MAKE_BIG16/32 and then we can just punt the problem to CFE to discourage developers from writing endian -specific code.

**Comment by jphickey** [comment]
Submitted nasa/cFE#1217 to stop CFE from depending on this, after which it can be removed from OSAL.
