### ISSUE TITLE
Scrub use of () in return statements

### ISSUE THREAD

**Issue by skliper** [nasa/osal#866]
**Is your feature request related to a problem? Please describe.**
Inconsistent use of (), style.  Example below but should fix all.
https://github.com/nasa/osal/blob/ead5723f59ee49b36a36d6cb66c4cfe680ebbd68/src/os/portable/os-impl-no-symtab.c#L50-L60

**Describe the solution you'd like**
Fix.

**Describe alternatives you've considered**
Leave as-is (future work)

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC, OSAL code review

**Comment by thnkslprpt** [comment]
Is there consensus on removing the parentheses? @astrogeco @skliper @jphickey 

There is ~400 instances of unnecessary parentheses surrounding the return values in the cFS codebase.
For comparison, there is ~4,000 instances of return statements that do not use parentheses for the return value.

From what I can tell no modern C/C++ coding standards require, or even prefer, parentheses around return values (e.g. MISRA, JSF, JPL, ESA etc.).

I'm happy to work on this but wanted to confirm if it's agreed upon first :-)

**Comment by skliper** [comment]
@dmknutsen - your call.  Simple style/consistency thing but could impact many repos.  Looks like a simple sed one-liner or similar to fix?

**Comment by thnkslprpt** [comment]
OK Thanks Jake/Dan.
I will take care of it.

**Comment by thnkslprpt** [comment]
For now, I will update only the return statements that return single values/terms like the one Jake linked to above.

I will leave the complex statements as is, even though they are logically unnecessary as well. For example:
https://github.com/nasa/osal/blob/38559d447fdeb1a85f8bb09938df30d7a50918a4/src/os/shared/src/osapi-time.c#L206-L210

I know some people prefer parentheses in these cases to make the arithmetical logic easier to break down in their head.

Happy to update the rest in future if it's considered prudent.
