### ISSUE TITLE
Scrub for include <> vs "" use (<> should be system only)

### ISSUE THREAD

**Issue by skliper** [nasa/osal#868]
**Is your feature request related to a problem? Please describe.**
<> used on non-system header includes.  Example:
https://github.com/nasa/osal/blob/ead5723f59ee49b36a36d6cb66c4cfe680ebbd68/src/os/shared/inc/os-shared-dir.h#L32

**Describe the solution you'd like**
Full scrub/fix

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC, OSAL code review

**Comment by zanzaben** [comment]
Missing Some utassert, uttest and utstubs

Here is one I found 
https://github.com/nasa/osal/blob/ead5723f59ee49b36a36d6cb66c4cfe680ebbd68/src/unit-test-coverage/shared/src/os-shared-coveragetest.h#L31-L33
