### ISSUE TITLE
Comments on header guard endif don't match ifdef

### ISSUE THREAD

**Issue by skliper** [nasa/osal#916]
**Is your feature request related to a problem? Please describe.**
For example:
https://github.com/nasa/osal/blob/ead5723f59ee49b36a36d6cb66c4cfe680ebbd68/src/os/inc/common_types.h#L31-L32
https://github.com/nasa/osal/blob/ead5723f59ee49b36a36d6cb66c4cfe680ebbd68/src/os/inc/common_types.h#L191

**Describe the solution you'd like**
Comments should be consistent w/ code

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by prsndp** [comment]
Hi @skliper Can I work on this issue if it's open??

**Comment by skliper** [comment]
@prsndp Thanks for the offer, but I think a script was just put together to automate this fix.
