### ISSUE TITLE
Why does UtPrintx have an infinite loop in it?

### ISSUE THREAD

**Issue by asgibson** [nasa/osal#964]
**Describe the bug**
Any use of UtPrintx results in an infinite printing of the given Memory and Length.

**To Reproduce**
1. Put UtPrintx in a unit test, give it an address and size (from 0 to max uint32)
2. Run tests
3. Enter loop

**Expected behavior**
1. Print the number of bytes given as _Length_ starting at the given address _Memory_ (with newline at end)
2. Return

**Code snips**
https://github.com/nasa/osal/blob/b37da18bd5efed6d86344e4cafaa42c833b015fb/ut_assert/src/uttools.c#L188-L207

**System observed on:**
 - RHEL 7.8

**Reporter Info**
Alan Gibson
NASA/GSFC 587

**Comment by skliper** [comment]
Guessing the intent was to break the output into lines, but definitely needs a fix.
