### ISSUE TITLE
Wrong token name used in accept call

### ISSUE THREAD

**Issue by excaliburtb** [nasa/osal#969]
https://github.com/nasa/osal/blob/afb5f7ba3ea48823e44490ce4258aa92a073087f/src/os/shared/src/osapi-sockets.c#L269

This is a bug. I think it should be conn_token.. not sock_token

**Comment by jphickey** [comment]
Yeah, this definitely looks like some sort of typo/copy+paste/merge issue, what I'm most confused about is why the functional test does not seem to catch this.  The memset after this line would clobber the socket record.  Maybe the test needs to do multiple connections or something.
